// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package recipe

import (
	"cookbook/api/recipe"
)

type ControllerV1 struct{}

func NewV1() recipe.IRecipeV1 {
	return &ControllerV1{}
}
