// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package scheduling

import (
	"cookbook/api/scheduling"
)

type ControllerV1 struct{}

func NewV1() scheduling.ISchedulingV1 {
	return &ControllerV1{}
}
