// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// aiGenerationsDao is the data access object for the table ai_generations.
// You can define custom methods on it to extend its functionality as needed.
type aiGenerationsDao struct {
	*internal.AiGenerationsDao
}

var (
	// AiGenerations is a globally accessible object for table ai_generations operations.
	AiGenerations = aiGenerationsDao{internal.NewAiGenerationsDao()}
)

// Add your custom methods and functionality below.
