// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// attachmentsDao is the data access object for the table attachments.
// You can define custom methods on it to extend its functionality as needed.
type attachmentsDao struct {
	*internal.AttachmentsDao
}

var (
	// Attachments is a globally accessible object for table attachments operations.
	Attachments = attachmentsDao{internal.NewAttachmentsDao()}
)

// Add your custom methods and functionality below.
