// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// favoriteItemsDao is the data access object for the table favorite_items.
// You can define custom methods on it to extend its functionality as needed.
type favoriteItemsDao struct {
	*internal.FavoriteItemsDao
}

var (
	// FavoriteItems is a globally accessible object for table favorite_items operations.
	FavoriteItems = favoriteItemsDao{internal.NewFavoriteItemsDao()}
)

// Add your custom methods and functionality below.
