// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// favoritesDao is the data access object for the table favorites.
// You can define custom methods on it to extend its functionality as needed.
type favoritesDao struct {
	*internal.FavoritesDao
}

var (
	// Favorites is a globally accessible object for table favorites operations.
	Favorites = favoritesDao{internal.NewFavoritesDao()}
)

// Add your custom methods and functionality below.
