// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// membersDao is the data access object for the table members.
// You can define custom methods on it to extend its functionality as needed.
type membersDao struct {
	*internal.MembersDao
}

var (
	// Members is a globally accessible object for table members operations.
	Members = membersDao{internal.NewMembersDao()}
)

// Add your custom methods and functionality below.
