// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// recipeTagsDao is the data access object for the table recipe_tags.
// You can define custom methods on it to extend its functionality as needed.
type recipeTagsDao struct {
	*internal.RecipeTagsDao
}

var (
	// RecipeTags is a globally accessible object for table recipe_tags operations.
	RecipeTags = recipeTagsDao{internal.NewRecipeTagsDao()}
)

// Add your custom methods and functionality below.
