// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// recipesDao is the data access object for the table recipes.
// You can define custom methods on it to extend its functionality as needed.
type recipesDao struct {
	*internal.RecipesDao
}

var (
	// Recipes is a globally accessible object for table recipes operations.
	Recipes = recipesDao{internal.NewRecipesDao()}
)

// Add your custom methods and functionality below.
