// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// schedulingsDao is the data access object for the table schedulings.
// You can define custom methods on it to extend its functionality as needed.
type schedulingsDao struct {
	*internal.SchedulingsDao
}

var (
	// Schedulings is a globally accessible object for table schedulings operations.
	Schedulings = schedulingsDao{internal.NewSchedulingsDao()}
)

// Add your custom methods and functionality below.
