// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// sqliteSequenceDao is the data access object for the table sqlite_sequence.
// You can define custom methods on it to extend its functionality as needed.
type sqliteSequenceDao struct {
	*internal.SqliteSequenceDao
}

var (
	// SqliteSequence is a globally accessible object for table sqlite_sequence operations.
	SqliteSequence = sqliteSequenceDao{internal.NewSqliteSequenceDao()}
)

// Add your custom methods and functionality below.
