// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"cookbook/internal/dao/internal"
)

// tagsDao is the data access object for the table tags.
// You can define custom methods on it to extend its functionality as needed.
type tagsDao struct {
	*internal.TagsDao
}

var (
	// Tags is a globally accessible object for table tags operations.
	Tags = tagsDao{internal.NewTagsDao()}
)

// Add your custom methods and functionality below.
