-- ============================================================================
-- 项目数据库初始化脚本（食谱 cookbook）
-- 数据库 : PostgreSQL（链接见 config.yaml 的 database.link，库名 cookbook）
-- 后端   : Go + GoFrame
-- 约定   :
--   1. 时间字段统一为 Unix 时间戳(秒, INTEGER/BIGINT)
--   2. 逻辑删除统一使用 is_deleted (0=正常, 1=已删除)
--   3. 主键统一为 id INTEGER GENERATED BY DEFAULT AS IDENTITY（显式插入 id 后需 setval 校准）
--   4. 字段含义用 -- 注释写在字段行尾（表注释写在 CREATE TABLE 前的 -- 块）
--   5. 不使用外键约束，引用完整性由 logic 层保证；引用缺失用 0 表示"无"
--   6. 列表型字段（食材/工具/步骤/标签/媒体）用 TEXT 列存 JSON 文本，应用层
--      (internal/model) 定义 Go 结构解析校验；需要按内容筛选的例外见各表注释
-- SQLite 兼容 : 历史脚本（hack/*.py 种子脚本）仍按 SQLite 3 编写，直连 SQLite 库使用
-- 流程   :
--   修改本文件 → 在 PG 上整体执行（幂等：表存在则跳过）
--   → gf gen dao（读 hack/config.yaml 的 link）→ dao/entity/do 自动生成
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 表: users 用户表
-- 注册用户，头像引用 attachments；收藏夹归属用户
-- 权限极简：只有 is_admin 一个角色位，首个注册用户自动成为管理员
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 主键
    username             TEXT    NOT NULL UNIQUE,             -- 登录名，唯一
    nickname             TEXT    NOT NULL DEFAULT '',         -- 昵称
    password_hash        TEXT    NOT NULL DEFAULT '',         -- 密码哈希(bcrypt)
    avatar_attachment_id INTEGER NOT NULL DEFAULT 0,           -- 头像附件 id → attachments.id，0=未设置
    is_admin             INTEGER NOT NULL DEFAULT 0 CHECK (is_admin IN (0, 1)), -- 0=普通用户 1=管理员（首个注册用户自动为管理员）
    status               INTEGER NOT NULL DEFAULT 1 CHECK (status IN (0, 1)), -- 0=禁用 1=正常
    last_login_at        INTEGER NOT NULL DEFAULT 0,          -- 最近登录时间 Unix 秒，0=从未登录
    created_at           INTEGER NOT NULL DEFAULT 0,          -- 创建时间 Unix 秒
    updated_at           INTEGER NOT NULL DEFAULT 0           -- 更新时间 Unix 秒
);

-- 幂等补列：已存在的库通过 ALTER 补 is_admin / last_login_at
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_admin INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at INTEGER NOT NULL DEFAULT 0;

-- ----------------------------------------------------------------------------
-- 表: user_sessions 登录会话表（双令牌）
-- 一次登录产生一对令牌（明文都不落库，只存 sha256 十六进制）：
--   · access_token  短效（2 小时）——每次请求带 Authorization: Bearer <token>
--   · refresh_token 长效（30 天，刷新时轮换并滑动续期）——access 过期后换新令牌对
-- 登出即删行；禁用账号 / 重置密码 / 取消管理员会清空该用户全部会话。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_sessions (
    id                 INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 主键
    user_id            INTEGER NOT NULL,             -- 归属用户 users.id
    access_token_hash  TEXT    NOT NULL UNIQUE,      -- 短效令牌 sha256，唯一
    access_expires_at  INTEGER NOT NULL DEFAULT 0,   -- 短效令牌过期时间 Unix 秒
    refresh_token_hash TEXT    NOT NULL UNIQUE,      -- 长效令牌 sha256，唯一
    expires_at         INTEGER NOT NULL DEFAULT 0,   -- 长效令牌过期时间 Unix 秒（刷新时滑动续期）
    created_at         INTEGER NOT NULL DEFAULT 0,   -- 创建时间 Unix 秒
    updated_at         INTEGER NOT NULL DEFAULT 0    -- 更新时间 Unix 秒（每次刷新令牌对时更新）
);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions (user_id); -- 按用户清理会话

-- 幂等补列：把早期单令牌结构升级为双令牌（本表 2026-09-20 引入，token_hash 作废）
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS access_token_hash  TEXT    NOT NULL DEFAULT '';
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS access_expires_at  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_sessions ADD COLUMN IF NOT EXISTS refresh_token_hash TEXT    NOT NULL DEFAULT '';
ALTER TABLE user_sessions DROP COLUMN IF EXISTS token_hash;

-- ----------------------------------------------------------------------------
-- 表: attachments 附件表
-- 全部文件附件统一入库登记：菜品图片/视频、用户头像、md 正文中的图片/附件。
-- 文件本体以 BYTEA 存本表 content 列，访问 URL 为 /attachments/{id}/content；
-- sha256 用于去重与秒传。被引用方（recipes.cover / steps.media / users.avatar）
-- 只存本表 id，附件真实内容（URL、宽高、时长）查询时 JOIN 或在 logic 层批量取。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attachments (
    id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,          -- 主键
    owner_user_id INTEGER NOT NULL DEFAULT 0,                 -- 上传者 users.id，0=系统
    kind          TEXT    NOT NULL DEFAULT 'image' CHECK (kind IN ('image', 'video', 'file', 'md_asset', 'avatar')), -- 用途：image=普通图片 video=视频 file=任意文件 md_asset=md 正文资源 avatar=头像
    file_name     TEXT    NOT NULL DEFAULT '',                -- 原始文件名
    storage_path  TEXT    NOT NULL UNIQUE,                    -- 存储相对路径，相对 manifest/attach/（如 202609/ab12.jpg）；历史数据兼容字段
    mime_type     TEXT    NOT NULL DEFAULT '',                -- MIME 类型
    size_bytes    BIGINT  NOT NULL DEFAULT 0,                 -- 文件大小(字节)
    width         INTEGER NOT NULL DEFAULT 0,                 -- 图片宽(像素)，非图片为 0
    height        INTEGER NOT NULL DEFAULT 0,                 -- 图片高(像素)，非图片为 0
    duration      INTEGER NOT NULL DEFAULT 0,                 -- 视频时长(秒)，非视频为 0
    sha256        TEXT    NOT NULL DEFAULT '',                -- 内容哈希，去重/秒传用
    is_deleted    INTEGER NOT NULL DEFAULT 0,                 -- 0=正常 1=已删除
    created_at    INTEGER NOT NULL DEFAULT 0,                 -- 创建时间 Unix 秒
    updated_at    INTEGER NOT NULL DEFAULT 0,                 -- 更新时间 Unix 秒
    content       BYTEA                                       -- 文件本体二进制内容
);
CREATE INDEX IF NOT EXISTS idx_attachments_owner ON attachments (owner_user_id, is_deleted); -- 按上传者查附件
CREATE INDEX IF NOT EXISTS idx_attachments_sha   ON attachments (sha256);                   -- 按哈希去重

-- 幂等补列：已存在的库通过 ALTER 补 content（CREATE TABLE IF NOT EXISTS 不会加列）
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS content BYTEA;

-- ----------------------------------------------------------------------------
-- 表: recipes 食谱表
-- 一条记录一道菜。正文不再单独存 markdown 列，内容由结构化列表承载：
-- 食材/工具/步骤均为 JSON 文本列，随行读写，不做跨表 JOIN。
-- 结构化筛选字段（用餐时间位掩码/难度/耗时/热量）单独成列；展示型
-- 列表（食材/工具/步骤/标签）用 JSON 文本列。
-- AI 可能生成不准确的内容：source/review_status 记录来源与人工核对状态。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recipes (
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- 主键
    user_id             INTEGER NOT NULL DEFAULT 0,           -- 作者 users.id，0=系统
    title               TEXT    NOT NULL,                     -- 菜谱标题
    summary             TEXT    NOT NULL DEFAULT '',          -- 一句话简介
    cover_attachment_id INTEGER NOT NULL DEFAULT 0,           -- 封面图 attachments.id，0=无封面
    tips                TEXT    NOT NULL DEFAULT '',          -- 注意事项，可空
    ingredients         TEXT    NOT NULL DEFAULT '[]',        -- 食材 JSON 数组：[{"name":"五花肉","amount":"500g","optional":0}]，保序
    tools               TEXT    NOT NULL DEFAULT '[]',        -- 工具 JSON 数组：["炒锅","砂锅"]，保序
    steps               TEXT    NOT NULL DEFAULT '[]',        -- 步骤 JSON 数组：[{"title":"焯水去腥","content":"第一步...","media":[1,2]}]，保序；title 可选，media 为 attachment id 数组
    meal_mask           INTEGER NOT NULL DEFAULT 0,           -- 适合用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐，0=未填；可按位或叠加（一菜可属多餐）
    calories            INTEGER NOT NULL DEFAULT 0,           -- 本菜谱总热量(kcal)，0=未填
    difficulty          INTEGER NOT NULL DEFAULT 0 CHECK (difficulty IN (0, 1, 2, 3)), -- 难度：0=未填 1=简单 2=中等 3=较难
    cook_minutes        INTEGER NOT NULL DEFAULT 0,           -- 耗时(分钟)，0=未填
    source              TEXT    NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'ai', 'import')), -- 来源：manual=手写 ai=AI 生成 import=导入
    ai_model            TEXT    NOT NULL DEFAULT '',          -- 生成模型名，source=ai 时有值
    review_status       INTEGER NOT NULL DEFAULT 0 CHECK (review_status IN (0, 1)), -- AI 内容人工核对：0=未核对 1=已核对
    sort                INTEGER NOT NULL DEFAULT 0,           -- 手动排序（设置页「菜谱管理」拖拽后按 1、2、3… 重写）；0=未参与排序，视为新菜谱置顶
    is_deleted          INTEGER NOT NULL DEFAULT 0,           -- 0=正常 1=已删除
    created_at          INTEGER NOT NULL DEFAULT 0,           -- 创建时间 Unix 秒
    updated_at          INTEGER NOT NULL DEFAULT 0            -- 更新时间 Unix 秒
);
CREATE INDEX IF NOT EXISTS idx_recipes_user   ON recipes (user_id, is_deleted);        -- 按作者查食谱
CREATE INDEX IF NOT EXISTS idx_recipes_review ON recipes (review_status) WHERE review_status = 0; -- 待核对清单（PG 部分索引）
-- 幂等删列：份量(人份)字段已从产品中移除（不展示、不参与任何逻辑），已存在的库同步删除
ALTER TABLE recipes DROP COLUMN IF EXISTS servings;
-- 幂等补列：手动排序位（首页菜谱墙与「菜谱管理」表格都按 sort ASC, id DESC 展示）
ALTER TABLE recipes ADD COLUMN IF NOT EXISTS sort INTEGER NOT NULL DEFAULT 0;

-- ----------------------------------------------------------------------------
-- 表: tags 标签表（只建结构，不预置数据）
-- 标签由前端「设置 → 标签管理」维护；脚本不插入任何标签行，
-- 以免重跑 init.sql 时把已删除/已改名的标签重新插回来、或与现有标签名冲突。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 主键
    name TEXT NOT NULL UNIQUE,                                -- 标签名，唯一
    sort INTEGER NOT NULL DEFAULT 0                           -- 展示排序（设置页拖拽排序后按 1、2、3… 重写）
);

-- ----------------------------------------------------------------------------
-- 表: recipe_tags 食谱-标签关联表
-- 多对多：一个食谱 0~N 个标签；复合主键防重复打标。
-- 保留独立表的原因：按标签筛选菜谱是核心查询路径，JSON 列无法走索引。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recipe_tags (
    recipe_id INTEGER NOT NULL,                               -- 食谱 recipes.id
    tag_id    INTEGER NOT NULL,                               -- 标签 tags.id
    PRIMARY KEY (recipe_id, tag_id)                           -- 同一食谱同一标签唯一
);
CREATE INDEX IF NOT EXISTS idx_recipe_tags_tag ON recipe_tags (tag_id);     -- 按标签反查食谱

-- ----------------------------------------------------------------------------
-- 表: members 家庭成员表
-- 记录成员角色与饮食限制，供筛选与后续 AI 排每周食谱参考
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS members (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,   -- 主键
    name       TEXT    NOT NULL,                     -- 成员名字，如 老张/小明
    role       TEXT    NOT NULL DEFAULT '',          -- 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
    note       TEXT    NOT NULL DEFAULT '',          -- 备注（口味、忌口、过敏等）
    sort       INTEGER NOT NULL DEFAULT 0,           -- 展示排序
    is_deleted INTEGER NOT NULL DEFAULT 0,           -- 0=正常 1=已删除
    created_at INTEGER NOT NULL DEFAULT 0,           -- 创建时间 Unix 秒
    updated_at INTEGER NOT NULL DEFAULT 0            -- 更新时间 Unix 秒
);
CREATE INDEX IF NOT EXISTS idx_members_deleted ON members (is_deleted); -- 查正常成员

-- 表: favorites 收藏夹表
-- 一个用户可建多个收藏夹
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favorites (
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,    -- 主键
    user_id             INTEGER NOT NULL DEFAULT 0,           -- 归属用户 users.id
    name                TEXT    NOT NULL,                     -- 收藏夹名
    description         TEXT    NOT NULL DEFAULT '',          -- 收藏夹描述
    cover_attachment_id INTEGER NOT NULL DEFAULT 0,           -- 收藏夹封面 attachments.id，0=无
    is_public           INTEGER NOT NULL DEFAULT 0 CHECK (is_public IN (0, 1)), -- 0=私密 1=公开
    sort                INTEGER NOT NULL DEFAULT 0,           -- 展示排序
    is_deleted          INTEGER NOT NULL DEFAULT 0,           -- 0=正常 1=已删除
    created_at          INTEGER NOT NULL DEFAULT 0,           -- 创建时间 Unix 秒
    updated_at          INTEGER NOT NULL DEFAULT 0            -- 更新时间 Unix 秒
);
CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites (user_id, is_deleted); -- 按用户查收藏夹

-- ----------------------------------------------------------------------------
-- 表: favorite_items 收藏条目表
-- 一个收藏夹可收藏多个食谱；复合主键防止重复收藏。
-- 保留独立表的原因：收藏需要 per-item 元数据（note/收藏时间）且反查
-- "被谁收藏"是真实查询；JSON 化会丢失这两个能力。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favorite_items (
    favorite_id INTEGER NOT NULL,                             -- 收藏夹 favorites.id
    recipe_id   INTEGER NOT NULL,                             -- 食谱 recipes.id
    note        TEXT    NOT NULL DEFAULT '',                  -- 收藏备注
    created_at  INTEGER NOT NULL DEFAULT 0,                   -- 收藏时间 Unix 秒
    PRIMARY KEY (favorite_id, recipe_id)                      -- 同一收藏夹同一食谱唯一
);
CREATE INDEX IF NOT EXISTS idx_favorite_items_recipe ON favorite_items (recipe_id); -- 反查"被谁收藏"

-- ----------------------------------------------------------------------------
-- 表: ai_generations AI 生成记录表
-- 保留 prompt 与模型原始输出，用于追溯"不准确"内容的来源与复现
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_generations (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,             -- 主键
    user_id    INTEGER NOT NULL DEFAULT 0,                    -- 发起用户 users.id
    recipe_id  INTEGER NOT NULL DEFAULT 0,                    -- 产出食谱 recipes.id，0=未落库/失败
    model      TEXT    NOT NULL DEFAULT '',                   -- 模型名
    prompt     TEXT    NOT NULL DEFAULT '',                   -- 用户输入/提示词
    raw_output TEXT    NOT NULL DEFAULT '',                   -- 模型原始输出
    status     INTEGER NOT NULL DEFAULT 0 CHECK (status IN (0, 1, 2)), -- 0=进行中 1=成功 2=失败
    error      TEXT    NOT NULL DEFAULT '',                   -- 失败原因
    created_at INTEGER NOT NULL DEFAULT 0                     -- 创建时间 Unix 秒
);

-- ----------------------------------------------------------------------------
-- 表: schedulings 食谱编排表
-- 按日期 + 用餐时段把菜谱排进周历；同一 (plan_date, meal) 可编排多个菜谱
-- （一餐多菜），由 sort 决定槽位内顺序。plan_date 存 YYYYMMDD 整数便于区间查询。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schedulings (
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,             -- 主键
    plan_date   INTEGER NOT NULL,                              -- 编排日期 YYYYMMDD，如 20260916
    meal        INTEGER NOT NULL CHECK (meal IN (1, 2, 4, 8)),-- 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
    recipe_id   INTEGER NOT NULL,                             -- 食谱 recipes.id
    note        TEXT    NOT NULL DEFAULT '',                   -- 编排备注
    sort        INTEGER NOT NULL DEFAULT 0,                    -- 同槽位内排序
    is_deleted  INTEGER NOT NULL DEFAULT 0,                    -- 0=正常 1=已删除
    created_at  INTEGER NOT NULL DEFAULT 0,                    -- 创建时间 Unix 秒
    updated_at  INTEGER NOT NULL DEFAULT 0                     -- 更新时间 Unix 秒
);
CREATE INDEX IF NOT EXISTS idx_schedulings_date ON schedulings (plan_date, is_deleted); -- 按日期区间查编排
-- 幂等删列：编排的份量同样不再使用（原先「0=用食谱默认」已无来源）
ALTER TABLE schedulings DROP COLUMN IF EXISTS servings;

-- ----------------------------------------------------------------------------
-- 表: settings 系统设置表（key-value 通用存储）
-- 通用设置项（如 AI 生图提示词模板）按 key 存取；value 为文本，
-- 支持长文本（提示词模板可达数 KB）。
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,             -- 主键
    key        TEXT    NOT NULL UNIQUE,             -- 设置键，如 image_gen_prompt
    value      TEXT    NOT NULL DEFAULT '',         -- 设置值（文本，长文本如提示词模板）
    is_deleted INTEGER NOT NULL DEFAULT 0,          -- 0=正常 1=已删除
    created_at INTEGER NOT NULL DEFAULT 0,          -- 创建时间 Unix 秒
    updated_at INTEGER NOT NULL DEFAULT 0           -- 更新时间 Unix 秒
);
