/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [POST] 上传附件
 *
 * **path:** /attachments
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = object
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 附件 id
 *   attachmentId?: number
 *   // 附件访问 URL
 *   url?: string
 * }
 * ```
 *
 */
type uploadResponse = ComponentTypes.Cookbook_api_attachment_v1_upload_res;
type uploadConfig = {
  body?: ComponentTypes.Cookbook_api_attachment_v1_upload_req;
};

export function upload(config: uploadConfig = {}): Promise<uploadResponse> {
  return request('POST', '/attachments', config);
}

/**
 * ---
 *
 * [GET] 获取附件内容
 *
 * **path:** /attachments/{id}/content
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 附件 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Query Parameters**
 * ```ts
 * type QueryParameters = {
 *   // 缩略图宽度（可选，仅支持 360，不放大）
 *   w?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type getContentResponse = ComponentTypes.Cookbook_api_attachment_v1_get_content_res;
type getContentConfig = {
  pathParams: {
    /**
     * 附件 id
     */

    id: number;
  };
  params?: {
    /**
     * 缩略图宽度（可选，仅支持 360，不放大）
     */

    w?: number;
  };
};

export function getContent(config: getContentConfig): Promise<getContentResponse> {
  return request('GET', '/attachments/{id}/content', config);
}
