/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
export type Cookbook_api_attachment_v1_get_content_res = object;
export type Cookbook_api_attachment_v1_upload_req = object;
export interface Cookbook_api_attachment_v1_upload_res {
  /**
   * 附件 id
   */

  attachmentId?: number;
  /**
   * 附件访问 URL
   */

  url?: string;
}
export type Cookbook_api_favorite_v1_add_item_res = object;
export interface Cookbook_api_favorite_v1_create_req {
  /**
   * 收藏夹名
   */

  name: string;
  /**
   * 收藏夹描述
   */

  description?: string;
  /**
   * 展示排序
   */

  sort?: number;
}
export interface Cookbook_api_favorite_v1_create_res {
  /**
   * 新收藏夹 id
   */

  id?: number;
}
export type Cookbook_api_favorite_v1_delete_res = object;
export interface Cookbook_api_favorite_v1_get_by_recipe_res {
  /**
   * 收藏夹 id 列表
   */

  favoriteIds?: number[];
}
export interface Cookbook_api_favorite_v1_get_list_res {
  /**
   * 收藏夹列表
   */

  list?: Cookbook_internal_model_favorite_folder[];
}
export interface Cookbook_api_favorite_v1_get_recipes_res {
  /**
   * 收藏的食谱列表
   */

  list?: Cookbook_internal_model_recipe_list_item[];
}
export type Cookbook_api_favorite_v1_remove_item_res = object;
export type Cookbook_api_favorite_v1_update_res = object;
export type Cookbook_api_hello_v1_hello_res = object;
export interface Cookbook_api_member_v1_create_req {
  /**
   * 成员名字
   */

  name: string;
  /**
   * 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
   */

  role?: string;
  /**
   * 备注（口味、忌口、过敏等）
   */

  note?: string;
  /**
   * 展示排序
   */

  sort?: number;
}
export interface Cookbook_api_member_v1_create_res {
  /**
   * 新成员 id
   */

  id?: number;
}
export type Cookbook_api_member_v1_delete_res = object;
export interface Cookbook_api_member_v1_get_list_res {
  /**
   * 成员列表
   */

  list?: Cookbook_internal_model_member_item[];
}
export type Cookbook_api_member_v1_update_res = object;
export interface Cookbook_api_recipe_v1_create_req {
  /**
   * 菜谱标题
   */

  title: string;
  /**
   * 一句话简介
   */

  summary?: string;
  /**
   * 封面附件 id，0=无封面
   */

  coverAttachmentId?: number;
  /**
   * 注意事项
   */

  tips?: string;
  /**
   * 食材列表
   */

  ingredients?: Cookbook_internal_model_recipe_ingredient_input[];
  /**
   * 工具列表
   */

  tools?: string[];
  /**
   * 标签 id 列表（分类），整体写入
   */

  tagIds?: number[];
  /**
   * 步骤列表
   */

  steps?: Cookbook_internal_model_recipe_step_item[];
  /**
   * 用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐；15=全部时段
   */

  mealMask?: number;
  /**
   * 难度：0=未填 1=简单 2=中等 3=较难
   */

  difficulty?: number;
  /**
   * 耗时(分钟)，0=未填
   */

  cookMinutes?: number;
  /**
   * 每份热量 kcal，0=未填
   */

  calories?: number;
}
export interface Cookbook_api_recipe_v1_create_res {
  /**
   * 新食谱 id
   */

  id?: number;
}
export type Cookbook_api_recipe_v1_delete_res = object;
export interface Cookbook_api_recipe_v1_get_list_res {
  /**
   * 当前页数据（空页为 []）
   */

  list?: Cookbook_internal_model_recipe_list_item[];
  /**
   * 过滤后总条数
   */

  total?: number;
}
export interface Cookbook_api_recipe_v1_get_one_res {
  /**
   * 食谱 id
   */

  id?: number;
  /**
   * 菜谱标题
   */

  title?: string;
  /**
   * 一句话简介
   */

  summary?: string;
  /**
   * 封面附件 id，0=无封面
   */

  coverAttachmentId?: number;
  /**
   * 封面图访问 URL，空=无封面
   */

  coverUrl?: string;
  /**
   * 注意事项
   */

  tips?: string;
  /**
   * 食材列表
   */

  ingredients?: Cookbook_internal_model_recipe_ingredient_input[];
  /**
   * 工具列表
   */

  tools?: string[];
  /**
   * 步骤列表（保序）
   */

  steps?: Cookbook_internal_model_recipe_step_item[];
  /**
   * 本菜谱总热量 kcal，0=未填
   */

  calories?: number;
  /**
   * 难度：0=未填 1=简单 2=中等 3=较难
   */

  difficulty?: number;
  /**
   * 耗时(分钟)，0=未填
   */

  cookMinutes?: number;
  /**
   * 适合用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐
   */

  mealMask?: number;
  /**
   * 菜谱标签列表
   */

  tags?: Cookbook_internal_model_tag_item[];
}
export type Cookbook_api_recipe_v1_update_res = object;
export interface Cookbook_api_scheduling_v1_create_req {
  /**
   * 编排日期 YYYYMMDD
   */

  planDate: number;
  /**
   * 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
   */

  meal: 1 | 2 | 4 | 8;
  /**
   * 食谱 id
   */

  recipeId: number;
  /**
   * 编排备注
   */

  note?: string;
  /**
   * 同槽位内排序
   */

  sort?: number;
}
export interface Cookbook_api_scheduling_v1_create_res {
  /**
   * 新编排条目 id
   */

  id?: number;
}
export type Cookbook_api_scheduling_v1_delete_res = object;
export interface Cookbook_api_scheduling_v1_get_list_res {
  /**
   * 编排列表
   */

  list?: Cookbook_internal_model_scheduling_item[];
}
export type Cookbook_api_scheduling_v1_update_res = object;
export interface Cookbook_api_setting_v1_get_list_res {
  /**
   * 全部设置项
   */

  settings?: Cookbook_internal_model_setting_item[];
}
export interface Cookbook_api_setting_v1_render_res {
  /**
   * 变量替换后的提示词全文
   */

  rendered?: string;
}
export interface Cookbook_api_setting_v1_upsert_req {
  /**
   * 设置项列表，整体写入
   */

  items: Cookbook_internal_model_setting_upsert_input[];
}
export type Cookbook_api_setting_v1_upsert_res = object;
export interface Cookbook_api_tag_v1_create_req {
  /**
   * 标签名
   */

  name: string;
}
export interface Cookbook_api_tag_v1_create_res {
  /**
   * 新标签 id
   */

  id?: number;
}
export interface Cookbook_api_tag_v1_delete_res {
  /**
   * 受影响菜谱数量（被移除该标签的菜谱数）
   */

  affectedRecipes?: number;
}
export interface Cookbook_api_tag_v1_get_list_res {
  /**
   * 标签列表
   */

  list?: Cookbook_internal_model_tag_item[];
}
export interface Cookbook_api_tag_v1_get_manage_list_res {
  /**
   * 标签管理列表
   */

  list?: Cookbook_internal_model_tag_manage_item[];
}
export interface Cookbook_api_tag_v1_reorder_req {
  /**
   * 拖拽后的标签 id 顺序（当前全部标签的完整顺序，从前往后）
   */

  ids: number[];
}
export type Cookbook_api_tag_v1_reorder_res = object;
export type Cookbook_api_tag_v1_update_res = object;
export interface Cookbook_api_user_v1_get_list_res {
  /**
   * 当前页数据（空页为 []）
   */

  list?: Cookbook_internal_model_user_item[];
  /**
   * 过滤后总条数
   */

  total?: number;
}
export interface Cookbook_api_user_v1_get_profile_res {
  /**
   * 用户 id
   */

  id?: number;
  /**
   * 登录名
   */

  username?: string;
  /**
   * 昵称
   */

  nickname?: string;
  /**
   * 是否管理员
   */

  isAdmin?: boolean;
}
export interface Cookbook_api_user_v1_login_req {
  /**
   * 登录名
   */

  username: string;
  /**
   * 密码
   */

  password: string;
}
export interface Cookbook_api_user_v1_login_res {
  /**
   * 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
   */

  token?: string;
  /**
   * 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
   */

  refreshToken?: string;
  /**
   * 访问令牌过期时间 Unix 秒
   */

  accessExpiresAt?: number;
  /**
   * 当前用户信息
   */

  user?: Cookbook_internal_model_user_profile;
}
export type Cookbook_api_user_v1_logout_req = object;
export type Cookbook_api_user_v1_logout_res = object;
export interface Cookbook_api_user_v1_refresh_req {
  /**
   * 登录或上次刷新返回的 refreshToken
   */

  refreshToken: string;
}
export interface Cookbook_api_user_v1_refresh_res {
  /**
   * 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
   */

  token?: string;
  /**
   * 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
   */

  refreshToken?: string;
  /**
   * 访问令牌过期时间 Unix 秒
   */

  accessExpiresAt?: number;
}
export interface Cookbook_api_user_v1_register_req {
  /**
   * 登录名
   */

  username: string;
  /**
   * 密码（明文，仅本次传输使用，落库为 bcrypt 哈希）
   */

  password: string;
  /**
   * 昵称，留空取用户名
   */

  nickname?: string;
}
export interface Cookbook_api_user_v1_register_res {
  /**
   * 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
   */

  token?: string;
  /**
   * 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
   */

  refreshToken?: string;
  /**
   * 访问令牌过期时间 Unix 秒
   */

  accessExpiresAt?: number;
  /**
   * 当前用户信息
   */

  user?: Cookbook_internal_model_user_profile;
}
export type Cookbook_api_user_v1_reset_password_res = object;
export type Cookbook_api_user_v1_update_res = object;
export interface Cookbook_internal_model_favorite_folder {
  /**
   * 收藏夹 id
   */

  id?: number;
  /**
   * 收藏夹名
   */

  name?: string;
  /**
   * 收藏夹描述
   */

  description?: string;
  /**
   * 收藏菜谱数
   */

  recipeCount?: number;
  /**
   * 展示排序
   */

  sort?: number;
}
export interface Cookbook_internal_model_member_item {
  /**
   * 成员 id
   */

  id?: number;
  /**
   * 成员名字
   */

  name?: string;
  /**
   * 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
   */

  role?: string;
  /**
   * 备注（口味、忌口、过敏等）
   */

  note?: string;
  /**
   * 展示排序
   */

  sort?: number;
}
export interface Cookbook_internal_model_recipe_ingredient_input {
  /**
   * 食材名，如 五花肉
   */

  name: string;
  /**
   * 用量，如 500g
   */

  amount?: string;
  /**
   * 0=必选 1=可选
   */

  optional?: number;
}
export interface Cookbook_internal_model_recipe_list_item {
  /**
   * 食谱 id
   */

  id?: number;
  /**
   * 菜谱标题
   */

  title?: string;
  /**
   * 一句话简介
   */

  summary?: string;
  /**
   * 封面附件 id，0=无封面
   */

  coverAttachmentId?: number;
  /**
   * 封面图访问 URL，空=无封面
   */

  coverUrl?: string;
  /**
   * 本菜谱总热量 kcal，0=未填
   */

  calories?: number;
  /**
   * 难度：0=未填 1=简单 2=中等 3=较难
   */

  difficulty?: number;
  /**
   * 耗时(分钟)，0=未填
   */

  cookMinutes?: number;
  /**
   * 被收藏次数（收藏夹数）
   */

  favoriteCount?: number;
  /**
   * 菜谱标签列表
   */

  tags?: Cookbook_internal_model_tag_item[];
}
export interface Cookbook_internal_model_recipe_step_item {
  /**
   * 步骤标题（可选），如「焯水去腥」
   */

  title?: string;
  /**
   * 步骤内容 markdown
   */

  content?: string;
  /**
   * 步骤媒体附件 id 列表
   */

  media?: number[];
}
export interface Cookbook_internal_model_scheduling_item {
  /**
   * 编排条目 id
   */

  id?: number;
  /**
   * 编排日期 YYYYMMDD，如 20260916
   */

  planDate?: number;
  /**
   * 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
   */

  meal?: number;
  /**
   * 食谱 id
   */

  recipeId?: number;
  /**
   * 食谱标题（冗余展示字段，列表接口回填）
   */

  recipeTitle?: string;
  /**
   * 食谱封面 URL，空=无封面
   */

  coverUrl?: string;
  /**
   * 编排备注
   */

  note?: string;
  /**
   * 同槽位内排序
   */

  sort?: number;
}
export interface Cookbook_internal_model_setting_item {
  /**
   * 设置键
   */

  key?: string;
  /**
   * 设置值
   */

  value?: string;
}
export interface Cookbook_internal_model_setting_upsert_input {
  /**
   * 设置键，如 image_gen_prompt
   */

  key: string;
  /**
   * 设置值（文本，长文本如提示词模板）
   */

  value?: string;
}
export interface Cookbook_internal_model_tag_item {
  /**
   * 标签 id
   */

  id?: number;
  /**
   * 标签名
   */

  name?: string;
  /**
   * 展示排序
   */

  sort?: number;
}
export interface Cookbook_internal_model_tag_manage_item {
  /**
   * 标签 id
   */

  id?: number;
  /**
   * 标签名
   */

  name?: string;
  /**
   * 展示排序
   */

  sort?: number;
  /**
   * 使用该标签的菜谱数量（不含已删除菜谱）
   */

  recipeCount?: number;
}
export interface Cookbook_internal_model_user_item {
  /**
   * 用户 id
   */

  id?: number;
  /**
   * 登录名
   */

  username?: string;
  /**
   * 昵称
   */

  nickname?: string;
  /**
   * 是否管理员
   */

  isAdmin?: boolean;
  /**
   * 状态：0=禁用 1=正常
   */

  status?: number;
  /**
   * 创建的菜谱数量（不含已删除）
   */

  recipeCount?: number;
  /**
   * 最近登录时间 Unix 秒，0=从未登录
   */

  lastLoginAt?: number;
  /**
   * 注册时间 Unix 秒
   */

  createdAt?: number;
}
export interface Cookbook_internal_model_user_profile {
  /**
   * 用户 id
   */

  id?: number;
  /**
   * 登录名
   */

  username?: string;
  /**
   * 昵称
   */

  nickname?: string;
  /**
   * 是否管理员
   */

  isAdmin?: boolean;
}
