/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询收藏夹列表
 *
 * **path:** /favorites
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 收藏夹列表
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 收藏夹 id
 *     id?: number
 *     // 收藏夹名
 *     name?: string
 *     // 收藏夹描述
 *     description?: string
 *     // 收藏菜谱数
 *     recipeCount?: number
 *     // 展示排序
 *     sort?: number
 *   }>
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_favorite_v1_get_list_res;
type getListConfig = {};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/favorites', config);
}

/**
 * ---
 *
 * [POST] 新建收藏夹
 *
 * **path:** /favorites
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 收藏夹名
 *   name: string
 *   // 收藏夹描述
 *   description?: string
 *   // 展示排序
 *   sort?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 新收藏夹 id
 *   id?: number
 * }
 * ```
 *
 */
type createResponse = ComponentTypes.Cookbook_api_favorite_v1_create_res;
type createConfig = {
  body?: ComponentTypes.Cookbook_api_favorite_v1_create_req;
};

export function create(config: createConfig = {}): Promise<createResponse> {
  return request('POST', '/favorites', config);
}

/**
 * ---
 *
 * [DELETE] 删除收藏夹
 *
 * **path:** /favorites/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 收藏夹 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type deleteResponse = ComponentTypes.Cookbook_api_favorite_v1_delete_res;
type deleteConfig = {
  pathParams: {
    /**
     * 收藏夹 id
     */

    id: number;
  };
};

const deleteFn = (config: deleteConfig): Promise<deleteResponse> => {
  return request('DELETE', '/favorites/{id}', config);
};
export { deleteFn as delete };

/**
 * ---
 *
 * [PUT] 编辑收藏夹
 *
 * **path:** /favorites/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 收藏夹 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 收藏夹名
 *   name: string
 *   // 收藏夹描述
 *   description?: string
 *   // 展示排序
 *   sort?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type updateResponse = ComponentTypes.Cookbook_api_favorite_v1_update_res;
type updateConfig = {
  pathParams: {
    /**
     * 收藏夹 id
     */

    id: number;
  };
  body?: {
    /**
     * 收藏夹名
     */

    name: string;
    /**
     * 收藏夹描述
     */

    description?: string;
    /**
     * 展示排序
     */

    sort?: number;
  };
};

export function update(config: updateConfig): Promise<updateResponse> {
  return request('PUT', '/favorites/{id}', config);
}

/**
 * ---
 *
 * [POST] 收藏食谱
 *
 * **path:** /favorites/{id}/items
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 收藏夹 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 收藏备注，可空
 *   note?: string
 *   // 食谱 id
 *   recipeId: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type addItemResponse = ComponentTypes.Cookbook_api_favorite_v1_add_item_res;
type addItemConfig = {
  pathParams: {
    /**
     * 收藏夹 id
     */

    id: number;
  };
  body?: {
    /**
     * 收藏备注，可空
     */

    note?: string;
    /**
     * 食谱 id
     */

    recipeId: number;
  };
};

export function addItem(config: addItemConfig): Promise<addItemResponse> {
  return request('POST', '/favorites/{id}/items', config);
}

/**
 * ---
 *
 * [DELETE] 取消收藏
 *
 * **path:** /favorites/{id}/items/{recipeId}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 收藏夹 id
 *   id: number
 *   // 食谱 id
 *   recipeId: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type removeItemResponse = ComponentTypes.Cookbook_api_favorite_v1_remove_item_res;
type removeItemConfig = {
  pathParams: {
    /**
     * 收藏夹 id
     */

    id: number;
    /**
     * 食谱 id
     */

    recipeId: number;
  };
};

export function removeItem(config: removeItemConfig): Promise<removeItemResponse> {
  return request('DELETE', '/favorites/{id}/items/{recipeId}', config);
}

/**
 * ---
 *
 * [GET] 收藏夹内食谱列表
 *
 * **path:** /favorites/{id}/recipes
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 收藏夹 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 收藏的食谱列表
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 食谱 id
 *     id?: number
 *     // 菜谱标题
 *     title?: string
 *     // 一句话简介
 *     summary?: string
 *     // 封面附件 id，0=无封面
 *     coverAttachmentId?: number
 *     // 封面图访问 URL，空=无封面
 *     coverUrl?: string
 *     // 每份热量 kcal，0=未填
 *     calories?: number
 *     // 难度：0=未填 1=简单 2=中等 3=较难
 *     difficulty?: number
 *     // 份量(人份)，0=未填
 *     servings?: number
 *     // 耗时(分钟)，0=未填
 *     cookMinutes?: number
 *     // 被收藏次数（收藏夹数）
 *     favoriteCount?: number
 *     // 菜谱标签列表
 *     // [items] start
 *     // [items] end
 *     tags?: Array<{
 *       // 标签 id
 *       id?: number
 *       // 标签名
 *       name?: string
 *       // 展示排序
 *       sort?: number
 *     }>
 *   }>
 * }
 * ```
 *
 */
type getRecipesResponse = ComponentTypes.Cookbook_api_favorite_v1_get_recipes_res;
type getRecipesConfig = {
  pathParams: {
    /**
     * 收藏夹 id
     */

    id: number;
  };
};

export function getRecipes(config: getRecipesConfig): Promise<getRecipesResponse> {
  return request('GET', '/favorites/{id}/recipes', config);
}

/**
 * ---
 *
 * [GET] 查询食谱被收藏的收藏夹
 *
 * **path:** /recipes/{id}/favorites
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 食谱 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 收藏夹 id 列表
 *   // [items] start
 *   // [items] end
 *   favoriteIds?: number[]
 * }
 * ```
 *
 */
type getByRecipeResponse = ComponentTypes.Cookbook_api_favorite_v1_get_by_recipe_res;
type getByRecipeConfig = {
  pathParams: {
    /**
     * 食谱 id
     */

    id: number;
  };
};

export function getByRecipe(config: getByRecipeConfig): Promise<getByRecipeResponse> {
  return request('GET', '/recipes/{id}/favorites', config);
}
