/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] You first hello api
 *
 * **path:** /hello
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type getResponse = ComponentTypes.Cookbook_api_hello_v1_hello_res;
type getConfig = {};

export function get(config: getConfig = {}): Promise<getResponse> {
  return request('GET', '/hello', config);
}
