/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
export { ApiError, request, type ApiRequestConfig } from './request';
import * as attachment from './attachment';
import * as user from './user';
import * as favorite from './favorite';
import * as hello from './hello';
import * as member from './member';
import * as recipe from './recipe';
import * as scheduling from './scheduling';
import * as setting from './setting';
import * as tag from './tag';

/** 按资源（operationId 前缀）分组的 API 命名空间，例如 `apis.skill.getList()` */
export const apis = {
  attachment,
  user,
  favorite,
  hello,
  member,
  recipe,
  scheduling,
  setting,
  tag
};
