/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询家庭成员
 *
 * **path:** /members
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 成员列表
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 成员 id
 *     id?: number
 *     // 成员名字
 *     name?: string
 *     // 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
 *     role?: string
 *     // 备注（口味、忌口、过敏等）
 *     note?: string
 *     // 展示排序
 *     sort?: number
 *   }>
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_member_v1_get_list_res;
type getListConfig = {};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/members', config);
}

/**
 * ---
 *
 * [POST] 新增成员
 *
 * **path:** /members
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 成员名字
 *   name: string
 *   // 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
 *   role?: string
 *   // 备注（口味、忌口、过敏等）
 *   note?: string
 *   // 展示排序
 *   sort?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 新成员 id
 *   id?: number
 * }
 * ```
 *
 */
type createResponse = ComponentTypes.Cookbook_api_member_v1_create_res;
type createConfig = {
  body?: ComponentTypes.Cookbook_api_member_v1_create_req;
};

export function create(config: createConfig = {}): Promise<createResponse> {
  return request('POST', '/members', config);
}

/**
 * ---
 *
 * [DELETE] 删除成员
 *
 * **path:** /members/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 成员 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type deleteResponse = ComponentTypes.Cookbook_api_member_v1_delete_res;
type deleteConfig = {
  pathParams: {
    /**
     * 成员 id
     */

    id: number;
  };
};

const deleteFn = (config: deleteConfig): Promise<deleteResponse> => {
  return request('DELETE', '/members/{id}', config);
};
export { deleteFn as delete };

/**
 * ---
 *
 * [PUT] 编辑成员
 *
 * **path:** /members/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 成员 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
 *   role?: string
 *   // 备注（口味、忌口、过敏等）
 *   note?: string
 *   // 展示排序
 *   sort?: number
 *   // 成员名字
 *   name: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type updateResponse = ComponentTypes.Cookbook_api_member_v1_update_res;
type updateConfig = {
  pathParams: {
    /**
     * 成员 id
     */

    id: number;
  };
  body?: {
    /**
     * 角色（爸爸 妈妈 儿子 妻子 妹妹，可自定义）
     */

    role?: string;
    /**
     * 备注（口味、忌口、过敏等）
     */

    note?: string;
    /**
     * 展示排序
     */

    sort?: number;
    /**
     * 成员名字
     */

    name: string;
  };
};

export function update(config: updateConfig): Promise<updateResponse> {
  return request('PUT', '/members/{id}', config);
}
