/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询食谱列表
 *
 * **path:** /recipes
 *
 * ---
 *
 * **Query Parameters**
 * ```ts
 * type QueryParameters = {
 *   // 页码，从 1 开始
 *   page?: number
 *   // 每页数量
 *   pageSize?: number
 *   // 关键词，匹配标题/简介
 *   keywords?: string
 *   // 标签 id 列表，多选为 AND 叠加（菜谱需同时含所有选中标签）
 *   // [items] start
 *   // [items] end
 *   tagIds?: number[]
 *   // 用餐时间筛选：1=早餐 2=午餐 4=晚餐 8=加餐，0/缺省=不筛
 *   meal?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 当前页数据（空页为 []）
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 食谱 id
 *     id?: number
 *     // 菜谱标题
 *     title?: string
 *     // 一句话简介
 *     summary?: string
 *     // 封面附件 id，0=无封面
 *     coverAttachmentId?: number
 *     // 封面图访问 URL，空=无封面
 *     coverUrl?: string
 *     // 每份热量 kcal，0=未填
 *     calories?: number
 *     // 难度：0=未填 1=简单 2=中等 3=较难
 *     difficulty?: number
 *     // 份量(人份)，0=未填
 *     servings?: number
 *     // 耗时(分钟)，0=未填
 *     cookMinutes?: number
 *     // 被收藏次数（收藏夹数）
 *     favoriteCount?: number
 *     // 菜谱标签列表
 *     // [items] start
 *     // [items] end
 *     tags?: Array<{
 *       // 标签 id
 *       id?: number
 *       // 标签名
 *       name?: string
 *       // 展示排序
 *       sort?: number
 *     }>
 *   }>
 *   // 过滤后总条数
 *   total?: number
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_recipe_v1_get_list_res;
type getListConfig = {
  params?: {
    /**
     * 页码，从 1 开始
     */

    page?: number;
    /**
     * 每页数量
     */

    pageSize?: number;
    /**
     * 关键词，匹配标题/简介
     */

    keywords?: string;
    /**
     * 标签 id 列表，多选为 AND 叠加（菜谱需同时含所有选中标签）
     */

    tagIds?: number[];
    /**
     * 用餐时间筛选：1=早餐 2=午餐 4=晚餐 8=加餐，0/缺省=不筛
     */

    meal?: number;
  };
};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/recipes', config);
}

/**
 * ---
 *
 * [POST] 新建食谱
 *
 * **path:** /recipes
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 菜谱标题
 *   title: string
 *   // 一句话简介
 *   summary?: string
 *   // 封面附件 id，0=无封面
 *   coverAttachmentId?: number
 *   // 注意事项
 *   tips?: string
 *   // 食材列表
 *   // [items] start
 *   // [items] end
 *   ingredients?: Array<{
 *     // 食材名，如 五花肉
 *     name: string
 *     // 用量，如 500g
 *     amount?: string
 *     // 0=必选 1=可选
 *     optional?: number
 *   }>
 *   // 工具列表
 *   // [items] start
 *   // [items] end
 *   tools?: string[]
 *   // 标签 id 列表（分类），整体写入
 *   // [items] start
 *   // [items] end
 *   tagIds?: number[]
 *   // 步骤列表
 *   // [items] start
 *   // [items] end
 *   steps?: Array<{
 *     // 步骤标题（可选），如「焯水去腥」
 *     title?: string
 *     // 步骤内容 markdown
 *     content?: string
 *     // 步骤媒体附件 id 列表
 *     // [items] start
 *     // [items] end
 *     media?: number[]
 *   }>
 *   // 用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐；15=全部时段
 *   mealMask?: number
 *   // 难度：0=未填 1=简单 2=中等 3=较难
 *   difficulty?: number
 *   // 耗时(分钟)，0=未填
 *   cookMinutes?: number
 *   // 每份热量 kcal，0=未填
 *   calories?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 新食谱 id
 *   id?: number
 * }
 * ```
 *
 */
type createResponse = ComponentTypes.Cookbook_api_recipe_v1_create_res;
type createConfig = {
  body?: ComponentTypes.Cookbook_api_recipe_v1_create_req;
};

export function create(config: createConfig = {}): Promise<createResponse> {
  return request('POST', '/recipes', config);
}

/**
 * ---
 *
 * [DELETE] 删除食谱
 *
 * **path:** /recipes/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 食谱 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type deleteResponse = ComponentTypes.Cookbook_api_recipe_v1_delete_res;
type deleteConfig = {
  pathParams: {
    /**
     * 食谱 id
     */

    id: number;
  };
};

const deleteFn = (config: deleteConfig): Promise<deleteResponse> => {
  return request('DELETE', '/recipes/{id}', config);
};
export { deleteFn as delete };

/**
 * ---
 *
 * [GET] 查询食谱详情
 *
 * **path:** /recipes/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 食谱 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 食谱 id
 *   id?: number
 *   // 菜谱标题
 *   title?: string
 *   // 一句话简介
 *   summary?: string
 *   // 封面附件 id，0=无封面
 *   coverAttachmentId?: number
 *   // 封面图访问 URL，空=无封面
 *   coverUrl?: string
 *   // 注意事项
 *   tips?: string
 *   // 食材列表
 *   // [items] start
 *   // [items] end
 *   ingredients?: Array<{
 *     // 食材名，如 五花肉
 *     name: string
 *     // 用量，如 500g
 *     amount?: string
 *     // 0=必选 1=可选
 *     optional?: number
 *   }>
 *   // 工具列表
 *   // [items] start
 *   // [items] end
 *   tools?: string[]
 *   // 步骤列表（保序）
 *   // [items] start
 *   // [items] end
 *   steps?: Array<{
 *     // 步骤标题（可选），如「焯水去腥」
 *     title?: string
 *     // 步骤内容 markdown
 *     content?: string
 *     // 步骤媒体附件 id 列表
 *     // [items] start
 *     // [items] end
 *     media?: number[]
 *   }>
 *   // 每份热量 kcal，0=未填
 *   calories?: number
 *   // 难度：0=未填 1=简单 2=中等 3=较难
 *   difficulty?: number
 *   // 份量(人份)，0=未填
 *   servings?: number
 *   // 耗时(分钟)，0=未填
 *   cookMinutes?: number
 *   // 适合用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐
 *   mealMask?: number
 *   // 菜谱标签列表
 *   // [items] start
 *   // [items] end
 *   tags?: Array<{
 *     // 标签 id
 *     id?: number
 *     // 标签名
 *     name?: string
 *     // 展示排序
 *     sort?: number
 *   }>
 * }
 * ```
 *
 */
type getOneResponse = ComponentTypes.Cookbook_api_recipe_v1_get_one_res;
type getOneConfig = {
  pathParams: {
    /**
     * 食谱 id
     */

    id: number;
  };
};

export function getOne(config: getOneConfig): Promise<getOneResponse> {
  return request('GET', '/recipes/{id}', config);
}

/**
 * ---
 *
 * [PUT] 编辑食谱
 *
 * **path:** /recipes/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 食谱 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 菜谱标题
 *   title?: string
 *   // 注意事项
 *   tips?: string
 *   // 食材列表，整体覆盖
 *   // [items] start
 *   // [items] end
 *   ingredients?: Array<{
 *     // 食材名，如 五花肉
 *     name: string
 *     // 用量，如 500g
 *     amount?: string
 *     // 0=必选 1=可选
 *     optional?: number
 *   }>
 *   // 标签 id 列表（分类），整体覆盖；nil=不修改 []=清空
 *   // [items] start
 *   // [items] end
 *   tagIds?: number[]
 *   // 难度：0=未填 1=简单 2=中等 3=较难
 *   difficulty?: number
 *   // 每份热量 kcal，0=未填
 *   calories?: number
 *   // 一句话简介
 *   summary?: string
 *   // 封面附件 id，0=清除封面
 *   coverAttachmentId?: number
 *   // 工具列表，整体覆盖
 *   // [items] start
 *   // [items] end
 *   tools?: string[]
 *   // 步骤列表，整体覆盖
 *   // [items] start
 *   // [items] end
 *   steps?: Array<{
 *     // 步骤标题（可选），如「焯水去腥」
 *     title?: string
 *     // 步骤内容 markdown
 *     content?: string
 *     // 步骤媒体附件 id 列表
 *     // [items] start
 *     // [items] end
 *     media?: number[]
 *   }>
 *   // 用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐；15=全部时段
 *   mealMask?: number
 *   // 耗时(分钟)，0=未填
 *   cookMinutes?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type updateResponse = ComponentTypes.Cookbook_api_recipe_v1_update_res;
type updateConfig = {
  pathParams: {
    /**
     * 食谱 id
     */

    id: number;
  };
  body?: {
    /**
     * 菜谱标题
     */

    title?: string;
    /**
     * 注意事项
     */

    tips?: string;
    /**
     * 食材列表，整体覆盖
     */

    ingredients?: ComponentTypes.Cookbook_internal_model_recipe_ingredient_input[];
    /**
     * 标签 id 列表（分类），整体覆盖；nil=不修改 []=清空
     */

    tagIds?: number[];
    /**
     * 难度：0=未填 1=简单 2=中等 3=较难
     */

    difficulty?: number;
    /**
     * 每份热量 kcal，0=未填
     */

    calories?: number;
    /**
     * 一句话简介
     */

    summary?: string;
    /**
     * 封面附件 id，0=清除封面
     */

    coverAttachmentId?: number;
    /**
     * 工具列表，整体覆盖
     */

    tools?: string[];
    /**
     * 步骤列表，整体覆盖
     */

    steps?: ComponentTypes.Cookbook_internal_model_recipe_step_item[];
    /**
     * 用餐时间位掩码：1=早餐 2=午餐 4=晚餐 8=加餐；15=全部时段
     */

    mealMask?: number;
    /**
     * 耗时(分钟)，0=未填
     */

    cookMinutes?: number;
  };
};

export function update(config: updateConfig): Promise<updateResponse> {
  return request('PUT', '/recipes/{id}', config);
}
