/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * NOTE: This file is generated only once and will NOT be overwritten on regeneration.
 * You can safely customize it to fit your needs.
 */
import { ofetch as $fetch } from 'ofetch';

/**
 * 单次 API 调用配置。
 *
 * 除 `pathParams` 外的全部字段会原样透传给 ofetch（$fetch），
 * 因此也支持 `timeout`、`retry`、`onRequest`、`onResponse` 等原生选项。
 */
export type ApiRequestConfig = {
  /** 路径参数，用于替换 path 中的 `{id}` 等占位符 */
  pathParams?: Record<string, string | number>;
} & Partial<Parameters<typeof $fetch>[1]>;

/** 后端统一响应信封（StandardRes，见 AGENTS.md），code=0 表示成功 */
interface StandardRes<T = unknown> {
  code: number;
  message: string;
  data: T;
}

/** 业务错误：HTTP 200 但信封 code != 0 */
export class ApiError extends Error {
  /** 后端业务错误码（gerror/gcode） */
  code: number;

  constructor(code: number, message: string) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
  }
}

function isStandardRes(value: unknown): value is StandardRes {
  return typeof value === 'object' && value !== null && 'code' in value && 'message' in value && 'data' in value;
}

/** 读取运行时 API 基地址；可用 NUXT_PUBLIC_API_BASE 环境变量覆盖 */
function resolveApiBase(): string {
  try {
    return (useRuntimeConfig().public?.apiBase as string | undefined) || 'http://127.0.0.1:8000';
  } catch {
    return 'http://127.0.0.1:8000';
  }
}

/**
 * 统一请求入口：替换路径参数后通过 $fetch 发起请求，
 * 并在 onResponse 中拆开 StandardRes 信封——生成的 Response 类型
 * 与 spec 一致（即信封的 data 部分）；code != 0 时抛出 {@link ApiError}。
 */
export function request<T>(
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD',
  path: string,
  config: ApiRequestConfig = {}
): Promise<T> {
  const { pathParams, ...options } = config;
  const url = pathParams
    ? path.replace(/\{([^}]+)\}/g, (_, key: string) =>
        pathParams[key] === undefined ? `{${key}}` : encodeURIComponent(String(pathParams[key]))
      )
    : path;
  const promise = $fetch(url, {
    method,
    baseURL: resolveApiBase(),
    ...options,
    onResponse({ response }) {
      const body: unknown = response._data;
      if (!isStandardRes(body)) return;
      if (body.code !== 0) {
        throw new ApiError(body.code, body.message);
      }
      response._data = body.data;
    }
  });
  // onResponse 已拆包为信封 data，与 spec 声明的响应类型一致
  return promise as Promise<T>;
}
