/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询食谱编排列表
 *
 * **path:** /schedulings
 *
 * ---
 *
 * **Query Parameters**
 * ```ts
 * type QueryParameters = {
 *   // 起始日期 YYYYMMDD（含），0=不限制
 *   startDate?: number
 *   // 结束日期 YYYYMMDD（含），0=不限制
 *   endDate?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 编排列表
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 编排条目 id
 *     id?: number
 *     // 编排日期 YYYYMMDD，如 20260916
 *     planDate?: number
 *     // 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
 *     meal?: number
 *     // 食谱 id
 *     recipeId?: number
 *     // 食谱标题（冗余展示字段，列表接口回填）
 *     recipeTitle?: string
 *     // 食谱封面 URL，空=无封面
 *     coverUrl?: string
 *     // 编排备注
 *     note?: string
 *     // 同槽位内排序
 *     sort?: number
 *   }>
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_scheduling_v1_get_list_res;
type getListConfig = {
  params?: {
    /**
     * 起始日期 YYYYMMDD（含），0=不限制
     */

    startDate?: number;
    /**
     * 结束日期 YYYYMMDD（含），0=不限制
     */

    endDate?: number;
  };
};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/schedulings', config);
}

/**
 * ---
 *
 * [POST] 新增食谱编排
 *
 * **path:** /schedulings
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 编排日期 YYYYMMDD
 *   planDate: number
 *   // 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
 *   meal: 1 | 2 | 4 | 8
 *   // 食谱 id
 *   recipeId: number
 *   // 编排备注
 *   note?: string
 *   // 同槽位内排序
 *   sort?: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 新编排条目 id
 *   id?: number
 * }
 * ```
 *
 */
type createResponse = ComponentTypes.Cookbook_api_scheduling_v1_create_res;
type createConfig = {
  body?: ComponentTypes.Cookbook_api_scheduling_v1_create_req;
};

export function create(config: createConfig = {}): Promise<createResponse> {
  return request('POST', '/schedulings', config);
}

/**
 * ---
 *
 * [DELETE] 删除食谱编排
 *
 * **path:** /schedulings/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 编排条目 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type deleteResponse = ComponentTypes.Cookbook_api_scheduling_v1_delete_res;
type deleteConfig = {
  pathParams: {
    /**
     * 编排条目 id
     */

    id: number;
  };
};

const deleteFn = (config: deleteConfig): Promise<deleteResponse> => {
  return request('DELETE', '/schedulings/{id}', config);
};
export { deleteFn as delete };

/**
 * ---
 *
 * [PUT] 编辑食谱编排
 *
 * **path:** /schedulings/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 编排条目 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 同槽位内排序
 *   sort?: number
 *   // 编排日期 YYYYMMDD
 *   planDate: number
 *   // 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
 *   meal: 1 | 2 | 4 | 8
 *   // 食谱 id
 *   recipeId: number
 *   // 编排备注
 *   note?: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type updateResponse = ComponentTypes.Cookbook_api_scheduling_v1_update_res;
type updateConfig = {
  pathParams: {
    /**
     * 编排条目 id
     */

    id: number;
  };
  body?: {
    /**
     * 同槽位内排序
     */

    sort?: number;
    /**
     * 编排日期 YYYYMMDD
     */

    planDate: number;
    /**
     * 用餐时段：1=早餐 2=午餐 4=晚餐 8=加餐
     */

    meal: 1 | 2 | 4 | 8;
    /**
     * 食谱 id
     */

    recipeId: number;
    /**
     * 编排备注
     */

    note?: string;
  };
};

export function update(config: updateConfig): Promise<updateResponse> {
  return request('PUT', '/schedulings/{id}', config);
}
