/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询设置列表
 *
 * **path:** /settings
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 全部设置项
 *   // [items] start
 *   // [items] end
 *   settings?: Array<{
 *     // 设置键
 *     key?: string
 *     // 设置值
 *     value?: string
 *   }>
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_setting_v1_get_list_res;
type getListConfig = {};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/settings', config);
}

/**
 * ---
 *
 * [PUT] 批量保存设置
 *
 * **path:** /settings
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 设置项列表，整体写入
 *   // [items] start
 *   // [items] end
 *   items: Array<{
 *     // 设置键，如 image_gen_prompt
 *     key: string
 *     // 设置值（文本，长文本如提示词模板）
 *     value?: string
 *   }>
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type upsertResponse = ComponentTypes.Cookbook_api_setting_v1_upsert_res;
type upsertConfig = {
  body?: ComponentTypes.Cookbook_api_setting_v1_upsert_req;
};

export function upsert(config: upsertConfig = {}): Promise<upsertResponse> {
  return request('PUT', '/settings', config);
}

/**
 * ---
 *
 * [GET] 渲染提示词模板
 *
 * **path:** /settings/{key}/render/{recipeId}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 食谱 id
 *   recipeId: number
 *   // 模板设置键，如 image_gen_prompt
 *   key: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 变量替换后的提示词全文
 *   rendered?: string
 * }
 * ```
 *
 */
type renderResponse = ComponentTypes.Cookbook_api_setting_v1_render_res;
type renderConfig = {
  pathParams: {
    /**
     * 食谱 id
     */

    recipeId: number;
    /**
     * 模板设置键，如 image_gen_prompt
     */

    key: string;
  };
};

export function render(config: renderConfig): Promise<renderResponse> {
  return request('GET', '/settings/{key}/render/{recipeId}', config);
}
