/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [GET] 查询标签列表
 *
 * **path:** /tags
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 标签列表
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 标签 id
 *     id?: number
 *     // 标签名
 *     name?: string
 *     // 展示排序
 *     sort?: number
 *   }>
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_tag_v1_get_list_res;
type getListConfig = {};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/tags', config);
}
