/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 *  - version
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by worma gen.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import { request } from './request';
import type * as ComponentTypes from './components';

/**
 * ---
 *
 * [POST] 用户登录
 *
 * **path:** /auth/login
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 登录名
 *   username: string
 *   // 密码
 *   password: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
 *   token?: string
 *   // 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
 *   refreshToken?: string
 *   // 访问令牌过期时间 Unix 秒
 *   accessExpiresAt?: number
 *   // 当前用户信息
 *   user?: {
 *     // 用户 id
 *     id?: number
 *     // 登录名
 *     username?: string
 *     // 昵称
 *     nickname?: string
 *     // 是否管理员
 *     isAdmin?: boolean
 *   }
 * }
 * ```
 *
 */
type loginResponse = ComponentTypes.Cookbook_api_user_v1_login_res;
type loginConfig = {
  body?: ComponentTypes.Cookbook_api_user_v1_login_req;
};

export function login(config: loginConfig = {}): Promise<loginResponse> {
  return request('POST', '/auth/login', config);
}

/**
 * ---
 *
 * [POST] 退出登录
 *
 * **path:** /auth/logout
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = object
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type logoutResponse = ComponentTypes.Cookbook_api_user_v1_logout_res;
type logoutConfig = {
  body?: ComponentTypes.Cookbook_api_user_v1_logout_req;
};

export function logout(config: logoutConfig = {}): Promise<logoutResponse> {
  return request('POST', '/auth/logout', config);
}

/**
 * ---
 *
 * [GET] 查询当前用户
 *
 * **path:** /auth/profile
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 用户 id
 *   id?: number
 *   // 登录名
 *   username?: string
 *   // 昵称
 *   nickname?: string
 *   // 是否管理员
 *   isAdmin?: boolean
 * }
 * ```
 *
 */
type getProfileResponse = ComponentTypes.Cookbook_api_user_v1_get_profile_res;
type getProfileConfig = {};

export function getProfile(config: getProfileConfig = {}): Promise<getProfileResponse> {
  return request('GET', '/auth/profile', config);
}

/**
 * ---
 *
 * [POST] 刷新登录令牌
 *
 * **path:** /auth/refresh
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 登录或上次刷新返回的 refreshToken
 *   refreshToken: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
 *   token?: string
 *   // 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
 *   refreshToken?: string
 *   // 访问令牌过期时间 Unix 秒
 *   accessExpiresAt?: number
 * }
 * ```
 *
 */
type refreshResponse = ComponentTypes.Cookbook_api_user_v1_refresh_res;
type refreshConfig = {
  body?: ComponentTypes.Cookbook_api_user_v1_refresh_req;
};

export function refresh(config: refreshConfig = {}): Promise<refreshResponse> {
  return request('POST', '/auth/refresh', config);
}

/**
 * ---
 *
 * [POST] 注册用户
 *
 * **path:** /auth/register
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 登录名
 *   username: string
 *   // 密码（明文，仅本次传输使用，落库为 bcrypt 哈希）
 *   password: string
 *   // 昵称，留空取用户名
 *   nickname?: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 访问令牌(access)，2 小时有效；请求头 Authorization: Bearer <token>
 *   token?: string
 *   // 刷新令牌(refresh)，30 天有效（滑动续期）；access 过期后调 /auth/refresh 换新
 *   refreshToken?: string
 *   // 访问令牌过期时间 Unix 秒
 *   accessExpiresAt?: number
 *   // 当前用户信息
 *   user?: {
 *     // 用户 id
 *     id?: number
 *     // 登录名
 *     username?: string
 *     // 昵称
 *     nickname?: string
 *     // 是否管理员
 *     isAdmin?: boolean
 *   }
 * }
 * ```
 *
 */
type registerResponse = ComponentTypes.Cookbook_api_user_v1_register_res;
type registerConfig = {
  body?: ComponentTypes.Cookbook_api_user_v1_register_req;
};

export function register(config: registerConfig = {}): Promise<registerResponse> {
  return request('POST', '/auth/register', config);
}

/**
 * ---
 *
 * [GET] 查询用户列表
 *
 * **path:** /users
 *
 * ---
 *
 * **Query Parameters**
 * ```ts
 * type QueryParameters = {
 *   // 页码，从 1 开始
 *   page?: number
 *   // 每页数量
 *   pageSize?: number
 *   // 关键词，匹配登录名/昵称
 *   keywords?: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = {
 *   // 当前页数据（空页为 []）
 *   // [items] start
 *   // [items] end
 *   list?: Array<{
 *     // 用户 id
 *     id?: number
 *     // 登录名
 *     username?: string
 *     // 昵称
 *     nickname?: string
 *     // 是否管理员
 *     isAdmin?: boolean
 *     // 状态：0=禁用 1=正常
 *     status?: number
 *     // 创建的菜谱数量（不含已删除）
 *     recipeCount?: number
 *     // 最近登录时间 Unix 秒，0=从未登录
 *     lastLoginAt?: number
 *     // 注册时间 Unix 秒
 *     createdAt?: number
 *   }>
 *   // 过滤后总条数
 *   total?: number
 * }
 * ```
 *
 */
type getListResponse = ComponentTypes.Cookbook_api_user_v1_get_list_res;
type getListConfig = {
  params?: {
    /**
     * 页码，从 1 开始
     */

    page?: number;
    /**
     * 每页数量
     */

    pageSize?: number;
    /**
     * 关键词，匹配登录名/昵称
     */

    keywords?: string;
  };
};

export function getList(config: getListConfig = {}): Promise<getListResponse> {
  return request('GET', '/users', config);
}

/**
 * ---
 *
 * [PUT] 修改用户
 *
 * **path:** /users/{id}
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 用户 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 昵称
 *   nickname?: string
 *   // 状态：0=禁用 1=正常（禁用会清空该用户登录态）
 *   status?: number
 *   // 是否管理员
 *   isAdmin?: boolean
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type updateResponse = ComponentTypes.Cookbook_api_user_v1_update_res;
type updateConfig = {
  pathParams: {
    /**
     * 用户 id
     */

    id: number;
  };
  body?: {
    /**
     * 昵称
     */

    nickname?: string;
    /**
     * 状态：0=禁用 1=正常（禁用会清空该用户登录态）
     */

    status?: number;
    /**
     * 是否管理员
     */

    isAdmin?: boolean;
  };
};

export function update(config: updateConfig): Promise<updateResponse> {
  return request('PUT', '/users/{id}', config);
}

/**
 * ---
 *
 * [PUT] 重置用户密码
 *
 * **path:** /users/{id}/password
 *
 * ---
 *
 * **Path Parameters**
 * ```ts
 * type PathParameters = {
 *   // 用户 id
 *   id: number
 * }
 * ```
 *
 * ---
 *
 * **RequestBody**
 * ```ts
 * type RequestBody = {
 *   // 新密码
 *   password: string
 * }
 * ```
 *
 * ---
 *
 * **Response**
 * ```ts
 * type Response = object
 * ```
 *
 */
type resetPasswordResponse = ComponentTypes.Cookbook_api_user_v1_reset_password_res;
type resetPasswordConfig = {
  pathParams: {
    /**
     * 用户 id
     */

    id: number;
  };
  body?: {
    /**
     * 新密码
     */

    password: string;
  };
};

export function resetPassword(config: resetPasswordConfig): Promise<resetPasswordResponse> {
  return request('PUT', '/users/{id}/password', config);
}
